### ISSUE TITLE
assert failed when training second epoch

### ISSUE THREAD

**Issue by xuduo35** [albumentations-team/autoalbument#11]
How can I fix this?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/cli/search.py", line 41, in main
    faa_searcher.search()
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/search.py", line 354, in search
    self.save()
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/search.py", line 312, in save
    self.save_policy()
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/search.py", line 274, in save_policy
    transform = self.models["policy"].create_transform(
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/policy.py", line 195, in create_transform
    OneOf([sp.create_transform(input_dtype, p=sub_policy_p) for sp in self.sub_policies], p=1),
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/policy.py", line 195, in <listcomp>
    OneOf([sp.create_transform(input_dtype, p=sub_policy_p) for sp in self.sub_policies], p=1),
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/policy.py", line 88, in create_transform
    return A.Sequential([stage.create_transform(input_dtype) for stage in self.stages], p=p)
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/policy.py", line 88, in <listcomp>
    return A.Sequential([stage.create_transform(input_dtype) for stage in self.stages], p=p)
  File "/usr/local/lib/python3.8/dist-packages/autoalbument/faster_autoaugment/policy.py", line 63, in create_transform
    assert sum(true_probabilities) <= 1.0
AssertionError

**Comment by creafz** [comment]
Hey, @xuduo35 

I guess that the assertion was triggered because of rounding errors for float probability values. I have released a new version of AutoAlbument (==0.3.1) that will show a RuntimeWarning instead of triggering an assertion in case of incorrect probability values. Generally speaking, probability values slightly above 1.0 should not affect augmentations' performance, but if after the update you will get a RuntimeWarning for incorrect probability values, please report the issue.

**Comment by xuduo35** [comment]
Thanks! I'll try later.
