### ISSUE TITLE
 Error loading module 'dataset.Cifar10SearchDataset'

### ISSUE THREAD

**Issue by LSnyd** [albumentations-team/autoalbument#21]
Hi there, 
I tried to run AutoAlbument with the CIFAR dataset, but I am running into the error below.
It seems like Hydra cannot find the dataset.Cifar10SearchDataset class, even though it is located in the dataset.py file in the same directory as the search.yaml file. I am also handing this exact directory to the autoalbument-search command: 

`autoalbument-search --config-dir /home/lisa/projects/structures/src/aug_search`

Does anyone have an idea where the error comes from? 

Best, 
Lisa

### Error
```
_version: 2
task: classification
policy_model:
  task_factor: 0.1
  gp_factor: 10
  temperature: 0.05
  num_sub_policies: 100
  num_chunks: 8
  operation_count: 4
  operations:
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB
    shift_r: true
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB
    shift_g: true
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB
    shift_b: true
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.RandomBrightness
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.RandomContrast
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.Solarize
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.HorizontalFlip
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.VerticalFlip
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.Rotate
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftX
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftY
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.Scale
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.CutoutFixedNumberOfHoles
  - _target_: autoalbument.faster_autoaugment.models.policy_operations.CutoutFixedSize
classification_model:
  _target_: autoalbument.faster_autoaugment.models.ClassificationModel
  num_classes: 10
  architecture: resnet18
  pretrained: false
data:
  dataset:
    _target_: dataset.Cifar10SearchDataset
    root: ~/data/cifar10
    train: true
    download: true
  input_dtype: uint8
  preprocessing: null
  normalization:
    mean:
    - 0.4914
    - 0.4822
    - 0.4465
    std:
    - 0.247
    - 0.243
    - 0.261
  dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 128
    shuffle: true
    num_workers: 8
    pin_memory: true
    drop_last: true
searcher:
  _target_: autoalbument.faster_autoaugment.search.FasterAutoAugmentSearcher
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  benchmark: true
  max_epochs: 40
  resume_from_checkpoint: null
optim:
  main:
    _target_: torch.optim.Adam
    lr: 0.001
    betas:
    - 0
    - 0.999
  policy:
    _target_: torch.optim.Adam
    lr: 0.001
    betas:
    - 0
    - 0.999
callbacks:
- _target_: autoalbument.callbacks.MonitorAverageParameterChange
- _target_: autoalbument.callbacks.SavePolicy
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_last: true
  dirpath: checkpoints
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: /home/lisa/projects/structures/src/aug_search/outputs/2021-05-17/17-07-59/tensorboard_logs
seed: 42

Working directory: /home/lisa/projects/structures/src/aug_search/outputs/2021-05-17/17-07-59
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pretrainedmodels-0.7.4-py3.9.egg/pretrainedmodels/models/dpn.py:255: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pretrainedmodels-0.7.4-py3.9.egg/pretrainedmodels/models/dpn.py:258: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pretrainedmodels-0.7.4-py3.9.egg/pretrainedmodels/models/dpn.py:262: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pretrainedmodels-0.7.4-py3.9.egg/pretrainedmodels/models/dpn.py:255: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pretrainedmodels-0.7.4-py3.9.egg/pretrainedmodels/models/dpn.py:258: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pretrainedmodels-0.7.4-py3.9.egg/pretrainedmodels/models/dpn.py:262: SyntaxWarning: "is" with a literal. Did you mean "=="?
[2021-05-17 17:08:01,579][pytorch_lightning.utilities.seed][INFO] - Global seed set to 42
[2021-05-17 17:08:02,488][autoalbument.faster_autoaugment.datamodule][INFO] - Preprocessing transform:
Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.4914, 0.4822, 0.4465], std=[0.247, 0.243, 0.261], max_pixel_value=255),
  ToTensorV2(always_apply=True, p=1.0, transpose_mask=True),
], p=1.0, bbox_params=None, keypoint_params=None, additional_targets={})
/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py:50: UserWarning: ModelCheckpoint(save_last=True, monitor=None) is a redundant configuration. You can save the last checkpoint with ModelCheckpoint(save_top_k=None, monitor=None).
  warnings.warn(*args, **kwargs)
[2021-05-17 17:08:02,618][pytorch_lightning.utilities.distributed][INFO] - GPU available: True, used: True
[2021-05-17 17:08:02,618][pytorch_lightning.utilities.distributed][INFO] - TPU available: None, using: 0 TPU cores
[2021-05-17 17:08:02,618][pytorch_lightning.accelerators.accelerator_connector][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]
Traceback (most recent call last):
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/utils.py", line 529, in _locate
    module = import_module(mod)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
ValueError: Empty module name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/utils.py", line 61, in call
    type_or_callable = _locate(cls)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/utils.py", line 532, in _locate
    raise ImportError(f"Error loading module '{path}'") from e
ImportError: Error loading module 'dataset.Cifar10SearchDataset'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lisa/miniconda3/envs/benchmark/bin/autoalbument-search", line 8, in <module>
    sys.exit(main())
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/autoalbument/cli/search.py", line 55, in main
    searcher.search()
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/autoalbument/faster_autoaugment/search.py", line 65, in search
    self.trainer.fit(self.model, datamodule=self.datamodule)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 488, in fit
    self.data_connector.prepare_data(model)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 59, in prepare_data
    self.trainer.datamodule.prepare_data()
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pytorch_lightning/core/datamodule.py", line 92, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py", line 40, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/autoalbument/faster_autoaugment/datamodule.py", line 23, in prepare_data
    self._instantiate_dataset()
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/autoalbument/faster_autoaugment/datamodule.py", line 73, in _instantiate_dataset
    dataset = instantiate(data_cfg.dataset, transform=transform)
  File "/home/lisa/miniconda3/envs/benchmark/lib/python3.9/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'dataset.Cifar10SearchDataset' : Error loading module 'dataset.Cifar10SearchDataset'
```

### dataset.py 

```
import cv2
import torchvision

cv2.setNumThreads(0)
cv2.ocl.setUseOpenCL(False)

class Cifar10SearchDataset(torchvision.datasets.CIFAR10):
    def __init__(self, root="~/data/cifar10", train=True, download=True, transform=None):
        super().__init__(root=root, train=train, download=download, transform=transform)

    def __getitem__(self, index):
        image, label = self.data[index], self.targets[index]

        if self.transform is not None:
            transformed = self.transform(image=image)
            image = transformed["image"]

        return image, label
```

### search.yaml

```

_version: 2  

task: classification 


policy_model:
 
  task_factor: 0.1
  gp_factor: 10
  temperature: 0.05
  num_sub_policies: 100
  num_chunks: 8
  operation_count: 4

classification_model:

    _target_: autoalbument.faster_autoaugment.models.ClassificationModel
    num_classes: 10
    architecture: resnet18
    pretrained: False


data:
  dataset:
    _target_: dataset.Cifar10SearchDataset
    root: ~/data/cifar10
    train: true
    download: true
  # Class for the PyTorch Dataset and arguments to it. AutoAlbument will create an object of this class using
  # the `instantiate` method from Hydra - https://hydra.cc/docs/next/patterns/instantiate_objects/overview/.
  #
  # Note that the target class value in the `_target_` argument should be located inside PYTHONPATH so Hydra could
  # find it. The directory with the config file is automatically added to PYTHONPATH, so the default value
  # `dataset.SearchDataset` points to the class `SearchDataset` from the `dataset.py` file. This `dataset.py` file is
  # located along with the `search.yaml` file in the same directory provided by `--config-dir`.
  #
  # As an alternative, you could provide a path to a Python file with the dataset using the `dataset_file` parameter
  # instead of the `dataset` parameter. The Python file should contain the implementation of a PyTorch dataset for
  # augmentation search. The dataset class should have named `SearchDataset`. The value in `dataset_file` could either
  # be a relative or an absolute path ; in the case of a relative path, the path should be relative to this config
  # file's location.
  #
  # - Example of a relative path:
  # dataset_file: dataset.py
  #
  # - Example of an absolute path:
  # dataset_file: /projects/pytorch/dataset.py
  #

  input_dtype: uint8
  preprocessing: null

  normalization:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.247, 0.243, 0.261]

  dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 128
    shuffle: true
    num_workers: 8
    pin_memory: true
    drop_last: true


optim:
  main:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0, 0.999]

  policy:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0, 0.999]

seed: 42 
hydra:
  run:
    dir: ${config_dir:}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}



trainer:
  max_epochs: 40
  benchmark: true
  gpus: 1
 

```

**Comment by LSnyd** [comment]
I got it working by renaming the class to SearchDataset and specifying the absolute dataset path in search_yaml:
`  dataset_file: /projects/..../dataset.py` 

I also had to comment out:
```
# dataset:
 #  _target_: dataset.Cifar10SearchDataset
 #  root: ~/data/cifar10
 #  train: true
 #  download: true
```

**Comment by eaxstump** [comment]
When you said you renamed the class to SearchDataset, are you referring to the class definition in dataset.py? I'm having the same issue but unfortunately your solution didn't work.
