### ISSUE TITLE
Error when using the 1.1.0 release of hydra-core  

### ISSUE THREAD

**Issue by howard-mahe** [albumentations-team/autoalbument#26]
Hello, I installed the library using pip which requires `hydra-core>=1.0`. But the code does not work since the release `1.1.0` of hydra-core 5 days ago.

Please find below the traceback of the error:
`autoalbument-search --config-dir autoalbument_search`
```
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/autoalbument/cli/search.py:15: UserWarning: register_resolver() is deprecated.
See https://github.com/omry/omegaconf/issues/426 for migration instructions.

  OmegaConf.register_resolver("config_dir", get_config_dir)
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'hydra/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'logger/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'callbacks/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'optim/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'trainer/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'searcher/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'data/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'semantic_segmentation_model/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'classification_model/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/core/default_element.py:122: UserWarning: In 'policy_model/default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
Traceback (most recent call last):
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 87, in run
    cfg = self.compose_config(
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 564, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 146, in load_configuration
    return self._load_configuration_impl(
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 249, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 515, in _compose_config_from_defaults_list
    loaded = self._load_single_config(default=default, repo=repo)
  File "/opt/miniconda3/envs/fasteraa/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 399, in _load_single_config
    raise ValueError(
ValueError: Config callbacks/default must be a Dictionary, got ConfigResult
```

**Comment by Puneethbandikatla** [comment]
I'm having the same issue. Were you able to resolve it? Kindly suggest

**Comment by howard-mahe** [comment]
I forced pip reinstalling hydra-core 1.0.6.
Btw, docker/requirements.txt is correct and use hydra-core 1.0.6 but the setup.py incorrectly mentions hydra-core>=1.0

**Comment by Puneethbandikatla** [comment]
Thanks a lot @howard-mahe . That helped me fix the issue.

**Comment by ihamdi** [comment]
This is what I had to do to get the cifar10 example to work:

- Upgrade Python from 3.6.13 to 3.7.11
- Downgrade Pytorch from 1.10.0 to 1.8.0
- Downgrade Hydra-Core from 1.1.0 to 1.0.6
- Change line 6 in envs/name/lib/site-packages/timm/models/layers/helper.py from "from torch._six import container_abcs" to "import collections.abc as container_abcs"
